### ISSUE TITLE
General implementation question

### ISSUE THREAD

**Issue by danchristian** [jamespegg/prismic-nuxt#1]
Thank you for creating this, there is so little documentation or examples for integrating Prismic with Nuxt, I had been struggling to get a working example up and running until finding this module. Excuse the higher level nature of these questions, I’m new to Prismic and feel like I’m missing some more general abstractions with the Nuxt implementation.

I had 3 questions covering the Installation, Querying and Templating aspects:

1) I presume installing `prismic-nuxt` negates the need for the any of the extra setup listed in the Prismic documentation? Such as including Prismic Toolbar (still not sure what that is), creating a separate Link Resolver function and the imports etc? Although looking through the `plugin.js` file it seems to follow the vanilla JS integration rather than the Vue.js one? 

2) Following the instructions on this repo, I have managed to pull in a test page title using `let document = await app.$prismic.api.getSingle('blog')`, so a success of some sorts.

I’m just not sure beyond that, how much of the Prismic documentation to follow. For example, I want to pull in a list of Blog Posts. Their Vue.js example looks like:

```
this.$prismic.client.query(
  this.$prismic.Predicates.at('document.type', 'blog_post'),
  { orderings : '[my.blog_post.date desc]' }
).then((response) => {
  // response is the response object, response.results holds the documents
})
```

Does that mean I need to use the `query` from the `plugin.js`, so something roughly like:

```
async asyncData({ query, error }) {
      let document = await query.$prismic.Predicates.at('document.type', 'blog_post')
```

Or should I be following the vanilla Javascript version? Or something different? I couldn't see similar examples in their documentation to the example on this repo.

3) With regards to the Templating example on this repo, I wasn’t sure if accessing the `$prismic.dom` was essentially a shortcut compared to the [Prismic documentation examples](https://prismic.io/docs/vuejs/templating/date) of `{{ document.title }}` type templating using the SFC structure (data function, methods etc). Seems slightly verbose to be referencing the Link Resolver on every DOM element I would bring in, but again, not sure if this was just a quick example or best practice etc

**Comment by jamespegg** [comment]
Hi @danchristian,

Sorry for taking a little while to get back to you!

To answer your first question; yes, using `prismic-nuxt` means you don't have to include the Prismic Toolbar or any of the other Prismic libraries (i.e. `prismic-javascript` and `prismic-dom`) for basic use. It is using the vanilla Prismic Javascript library because at the time the Vue implementation didn't play nicely with server-side rendering (which is the main reason I put this together).

In terms of following the Prismic documentation, I'd stick to their vanilla Javascript documentation. So with your example above, you'd want to do something like this;

```javascript
async asyncData({ app, error }) {
    let document = await app.$prismic.query(
        Prismic.Predicates.at('document.type', 'blog_post')
    )
}
```

In this example you'll want to install Prismic as a full dependency (rather than relying on a peer dependency) and import it using `import Prismic from 'prismic-javascript'`. Although to be honest, I might just make it available via `prismic-nuxt` to make things a bit easier.

So with templating, anything which isn't rich text or a link can be access directly with things like `{{ document.title }}`. However with rich text and links, Prismic resolves the URL's at runtime rather than at the API layer, which is why you have to use Prismic DOM.

I had a long think about whether to abstract Prismic DOM so that you didn't have to manually pass in the link resolver every time, but I felt this would add a level of fragility to this library. Whenever Prismic updates their package, I would have to make sure I update my abstractions too. This just opens a whole can of worms.
