### ISSUE TITLE
Access to Locale in linkResolver

### ISSUE THREAD

**Issue by suplere** [jamespegg/prismic-nuxt#23]
Hi,
My problem is how can as handle links in RichText base on the app i18 locale.

I have one single type  - homepage, repetable types product and page.

If is page have has default locale all works fine (_/products/one_), but for example for **en** locale i need page in in this format _/en/products/one_.

I have this link resolver : 
`if (doc.type === 'home') { return '/'}`
for product type i have this :
`if (doc.type === 'product') {return '/products/' + doc.uid}`

Is there a way how can I access app locale in linkResolver?

**Comment by jamespegg** [comment]
This is probably a question for the official Prismic library teams, but you should be able to access the language of the document through `doc.lang`. I found this example, which might help; https://github.com/levimykel/prismic-i18n-example/blob/master/prismic-configuration.js

**Comment by timdiacon** [comment]
I have the same question. When using i18n I need to be able to call the method app.localePath() to convert links into the correct version for the current locale. The problem is "app" is not available within the link resolver function.

Prior to using the prismic-module my solution was to make app available by setting up the link resolver as a method on Vue.prototype as below

`export default ({ app }) => {
	Vue.prototype.$linkResolver = function(doc, parent) {
         // app.locale() used here
	}
}`

This would still work but rather than have to call the link-resolver manually in my templates I really want to be able to use the <prismic-link> tag but somehow be able to access 'app' within the link resolver method.

Could it be possible for <prismic-link> to pass through the context as an additional parameter along with the doc when is calling the link resolver?
