### ISSUE TITLE
How to add a htmlSerializer?

### ISSUE THREAD

**Issue by michaelpumo** [jamespegg/prismic-nuxt#7]
I see the linkResolver is set up on the Nuxt config but when I add another method for a htmlSerializer, it's undefined in my templates.

Is there a correct way to do this with Nuxt?

**Comment by jamespegg** [comment]
As a temporary workaround you can follow the [official Prismic guidelines](https://prismic.io/docs/javascript/beyond-the-api/html-serializer), put the HTML Serializer in a separate file, include it in your component’s data model and use it whenever you call `asHtml`.

With that said, I think it’s worth building this into the plugin so that it behaves in the same way as the link resolver. If you’re happy to wait, I could fit that in the release after next (i.e. v0.3.0) or I’m happy to accept a pull request in time for v0.2.0.

**Comment by michaelpumo** [comment]
Ah yes, this is what I ended up doing. It wasn't a huge roadblock but it's always nice to have the wrapper do this for you I guess.
